# Generated by Django 2.0.3 on 2018-03-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeuser',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policeuser',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
