# Generated by Django 2.0.3 on 2018-03-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_constable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='constable',
            new_name='RPF',
        ),
    ]
