# Generated by Django 2.0.3 on 2018-03-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registersos',
        ),
    ]
