# Generated by Django 2.0.3 on 2018-03-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0002_remove_firstruc_tripstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstruc',
            name='location',
        ),
        migrations.AddField(
            model_name='firstruc',
            name='latitute',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
