# Generated by Django 2.0.3 on 2018-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0007_auto_20180328_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstruc',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=13.0833, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='firstruc',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=80.2833, max_digits=6, null=True),
        ),
    ]
