# Generated by Django 2.0.3 on 2018-03-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0009_auto_20180328_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstruc',
            name='nearest',
            field=models.CharField(default='Jaipur', max_length=250),
        ),
        migrations.AlterField(
            model_name='firstruc',
            name='latitude',
            field=models.CharField(default='20.0', max_length=250),
        ),
        migrations.AlterField(
            model_name='firstruc',
            name='longitude',
            field=models.CharField(default='77.0', max_length=250),
        ),
    ]
