# Generated by Django 2.0.3 on 2018-03-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0011_auto_20180330_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstruc',
            name='latitude',
            field=models.CharField(default='9.9252', max_length=250),
        ),
        migrations.AlterField(
            model_name='firstruc',
            name='longitude',
            field=models.CharField(default='78.11988', max_length=250),
        ),
        migrations.AlterField(
            model_name='firstruc',
            name='nearest',
            field=models.CharField(default='Coimbatore', max_length=250),
        ),
    ]
