# Generated by Django 2.0.3 on 2018-03-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0013_auto_20180330_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstruc',
            name='latitude',
            field=models.CharField(default='12.916', max_length=250),
        ),
        migrations.AlterField(
            model_name='firstruc',
            name='longitude',
            field=models.CharField(default='79.132', max_length=250),
        ),
        migrations.AlterField(
            model_name='firstruc',
            name='nearest',
            field=models.CharField(default='Chennai', max_length=250),
        ),
    ]
