# Generated by Django 2.0.3 on 2018-03-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0016_auto_20180330_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstruc',
            name='address',
        ),
        migrations.RemoveField(
            model_name='firstruc',
            name='description',
        ),
        migrations.RemoveField(
            model_name='firstruc',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='firstruc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='firstruc',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='firstruc',
            name='name',
        ),
    ]
